### ISSUE TITLE
Autocomplete after dot

### ISSUE THREAD

**Issue by sporto** [atishay/vscode-allautocomplete#16]
I tried this with Elm but cannot get autocomplete after `.`

e.g. I have

```
user =
    { name = "Sam" }

user.
```

After typing `user.n` I would expect to see `name` as suggestion.
Any help on this would be great, thanks

**Comment by atishay** [comment]
The [VSCode API](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L6090) makes this kind of completion very difficult. The ranking of completion providers is based on a matching algorithm and VSCode does not want to show too many completion providers. It seems like the ranking for `.` character is different from other characters. I will try and look for a solution where I can match the `.` character ranking for default types. That you for informing me.

**Comment by atishay** [comment]
The [getWordRangeAtPosition](https://github.com/Microsoft/vscode/blob/05c70a3ad836e0a9d2bba86b06098be4fb0c7c50/src/vs/vscode.d.ts#L218)API is giving wrong value, i.e. if you type `user.n`, the other languages give `n` as the word range at the last position while the elm language server gives `usern`. This should be fixed by the language server. As a work around, setting the whitespace splitters in AllAutocomplete will force autocomplete to ignore language based settings. I will be updating the splitter in the next version.

**Comment by atishay** [comment]
Created https://github.com/Krzysztof-Cieslak/vscode-elm/issues/201

**Comment by atishay** [comment]
Added workaround in 0.0.12
