### ISSUE TITLE
Investigate issues with Rubocop extension

### ISSUE THREAD

**Issue by atishay** [atishay/vscode-allautocomplete#2]
See https://github.com/Microsoft/vscode/issues/5312#issuecomment-302442687

**Comment by atishay** [comment]
Not able to reproduce. Need help reducing from @jilustrisimo

**Comment by jilustrisimo** [comment]
Unsure as to what caused it, all settings for rubocop seemed fine.  I reinstalled the rubocop extension and everything, including autocomplete, was functional. It was odd because I had only installed All Autocomplete when the error began and rubocop didn't have a recent update.  Either way,  you can close this issue.  If it happens again and I can determine the bug comes from All Autocomplete I will open a new and more detailed issue.  Again, thanks for making this extension.

**Comment by atishay** [comment]
Thanks. I will mark this closed.
